### PR TITLE
add some foundation related resources

### PR DESCRIPTION
**Pull request by ldpliu**
**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>

**Description of Changes:**

**What resource is being added**: <resource name> | N/A
clusterpools.hive.openshift.io
clusterclaims.hive.openshift.io
machinepools.hive.openshift.io 
managedclustersets.cluster.open-cluster-management.io
managedclustersetbindings.cluster.open-cluster-management.io
managedclusterimageregistries.imageregistry.open-cluster-management.io

**Is this a Hub or Managed cluster change?:**
Hub Cluster

**Notes:**

related pr in mce must-gather: https://github.com/stolostron/backplane-must-gather/pull/18

### CODE REVIEW

**Review by eemurphy — APPROVED** [review]
/lgtm

**Comment by ldpliu** [comment]
@eemurphy It still need tje `approve` label, Thanks...

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Pull request merged**
