### PR TITLE
collect output for ramen resources

### PR DESCRIPTION
**Pull request by yati1998**
This commit collects the output for the
following command:
* oc describe mirrorpeers
* oc get and describe manifestwork
* oc get and describe managedclsuterview

Signed-off-by: yati1998 <ypadia@redhat.com>

### CODE REVIEW

**Comment by yati1998** [comment]
@mqhackett @ShyamsundarR can you please review this PR.

**Review by ShyamsundarR — COMMENTED** [review]
LGTM! As it stands the PR is fine.

I am wondering if we need to reduce scope of resources we gather (or such intelligence is even acceptable in a must-gather). For example:
- Gather placement rules that only state scheduler as "ramen"
- Gather subscriptions that point to above placement rules
- Gather manifest work and managed cluster view for managed clusters that are part of DRPolicy
and such...

We can tackle these as a separate PR if such actions/filters are acceptable to reduce must-gather time/resources/size.

**Comment by yati1998** [comment]
> LGTM! As it stands the PR is fine.
> 
> I am wondering if we need to reduce scope of resources we gather (or such intelligence is even acceptable in a must-gather). For example:
> 
> * Gather placement rules that only state scheduler as "ramen"
> * Gather subscriptions that point to above placement rules
> * Gather manifest work and managed cluster view for managed clusters that are part of DRPolicy
>   and such...
> 
> We can tackle these as a separate PR if such actions/filters are acceptable to reduce must-gather time/resources/size.

I don't think it can be done now, but yeah sure we can tackle it if required. For now, I would like this PR to get merged so that we can collect these resources.

**Comment by mqhackett** [comment]
@yati1998 Are these ramen resources expected to be available on all clusters? I'm curious what happens when they aren't there. Is there an error thrown?

**Comment by yati1998** [comment]
It is only in the Hub cluster. And there is a check to collect the resources only when it's a hub cluster. So IMO, there shouldn't be any error.

**Pull request merged**
