### PR TITLE
Add subscription report

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: Maggie Chen <magchen@redhat.com>

**Related Issue:**  https://github.com/stolostron/backlog/issues/24568

**Description of Changes:**

**What resource is being added**: SubscriptionReport, subscriptionstatus, ApplicationSet, Argo application resource

**Is this a Hub or Managed cluster change?:**
Hub Cluster | Managed Cluster | N/A
Both

**Notes:**

### CODE REVIEW

**Review by fxiang1 — APPROVED** [review]
LGTM! Thanks Maggie!

**Comment by chenz4027** [comment]
Hey @fxiang1 , @xiangjingli pointed out that argo resources will cause errors as they depend on Argo crds, which are installed independently by Argo operators. Removing them for now :(

Error: 
```➜  test     oc adm inspect applicationsets.argoproj.io --all-namespaces  --dest-dir=must-gather
I0822 15:45:24.414405   58646 request.go:621] Throttling request took 1.067942544s, request: GET:https://api.cs-aws-411-9xl27.dev02.red-chesterfield.com:6443/apis/machineconfiguration.openshift.io/v1?timeout=32s
error: the server doesn't have a resource type "applicationsets"
➜  test
```

**Comment by fxiang1** [comment]
@chenz4027 I guess we don't need those for now :)

**Review by fxiang1 — APPROVED** [review]
LGTM!

**Comment by chenz4027** [comment]
Thanks @fxiang1 
Looks like we don't have permission

/assign @jlpadilla @gurnben

**Review by jlpadilla — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
