### PR TITLE
change image to point to stolostron repo in README

### PR DESCRIPTION
**Pull request by eemurphy**
Signed-off-by: Erin Murphy <erinmurp@redhat.com>

**Related Issue:**  https://github.com/stolostron/backlog/issues/22225

**Description of Changes:** Update the must-gather images to stolostron URL

**What resource is being added**: N/A

**Is this a Hub or Managed cluster change?:** 
N/A

### CODE REVIEW

**Comment by SherinV** [comment]
Put a /hold as 2.5 is in code freeze now. Will need approval from release-manager before merging into 2.5.

**Comment by jlpadilla** [comment]
Reopening. This PR was approved but not merged. Currently the 2.5 release is frozen, will merge as soon as we start release-2.6

**Comment by jlpadilla** [comment]
/unhold

Verified prow has been updated for release-26

**Pull request merged**
