### PR TITLE
Fix FPS compliance on container image

### PR DESCRIPTION
**Pull request by douglascamata**
**Related Issue:**  https://issues.redhat.com/browse/ACM-10920

**Description of Changes:** 

- Use `registry.access.redhat.com/openshift4/ose-cli` as base image to get the `oc` binary on all Dockerfiles.

**What resource is being added**: | N/A

**Is this a Hub or Managed cluster change?:**  N/A

**Notes:** the scan's details are in the JIRA. We could in the future even consolidate the two Dockerfiles into one.

### CODE REVIEW

**Comment by douglascamata** [comment]
/cc @rh-dluong @Kyl-Bempah @dhaiducek 

Could you have a look at this, please? 🙏

**Comment by douglascamata** [comment]
Sorry, my previous comment might not be clear. Did that Konflux PR fix the FIPS compliance?

**Comment by douglascamata** [comment]
Closed as this should be solved by a previously merged PR.

**Comment by dhaiducek** [comment]
Thanks, @douglascamata! Yes, we should be able to close this PR. I'll check in downstream and update the issue with what I find.

**Pull request closed without merging**
